# Generated by Django 2.1 on 2018-12-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventExport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=6)),
                ('token', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('start_date', models.CharField(max_length=10)),
                ('start_time', models.CharField(max_length=5)),
                ('end_date', models.CharField(max_length=10)),
                ('end_time', models.CharField(max_length=5)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
